# Premenné pre kompilátor a prepínače
CC = gcc
CFLAGS = -Wall -Wextra -g

# POVINNÝ CIEĽ podľa zadania
compile:
	$(CC) $(CFLAGS) zadanie1.c -o zadanie1.exe

# Pomocný cieľ na vymazanie skompilovaného programu
clean:
	rm -f zadanie1.exe