# Premenné pre kompilátor a prepínače
CC = gcc
CFLAGS = -Wall -Wextra -g

# POVINNÝ CIEĽ podľa zadania
compile:
	$(CC) $(CFLAGS) zadanie2.c -o zadanie2.exe

# Pomocný cieľ na vymazanie skompilovaného programu
clean:
	rm -f zadanie2.exe